online_theater/apps/movie/urls.py
from django.urls import path
from .views import CartoonAddReview, MovieDetailView, AddReview, ActorView, AddStarRating, MovieSearch, SeriesSearch, CartoonSearch, AnimeSearch, movie_genre_view, series_genre_view, SeriesView, CartoonView, AnimeView, cartoon_genre_view, anime_genre_view, SeriesDetailView, CartoonDetailView, AnimeDetailView, AllDataViews, all, SeriesAddReview, MoviesView, AnimeAddReview
from .filters import FilterMoviesView, JsonFilterView

urlpatterns = [
    path('', all, name='base'),
    path('movies/', MoviesView.as_view(), name='movies_list'),
    path('series/', SeriesView.as_view(), name='series_list'),
    path('cartoon/', CartoonView.as_view(), name='cartoon_list'),
    path('anime/', AnimeView.as_view(), name='anime_list'),
    path('all/', AllDataViews.as_view(), name = 'all_data_list'),
    path('filter/', FilterMoviesView.as_view(), name = "filter"),
    path('movie/search/', MovieSearch.as_view(), name = 'movie_search'),
    path('video/', all, name='video'),
    path('series/search/', SeriesSearch.as_view(), name = 'series_search'),
    path('cartoon/search/', CartoonSearch.as_view(), name = 'cartoon_search'),
    path('anime/search/', AnimeSearch.as_view(), name = 'anime_search'),
    path('movies/<str:url>/', movie_genre_view, name='movie_genre_lists'),
    path('series_genre/<str:url>/', series_genre_view, name='series_genre_ist'),
    path('cartoon_genre/<str:url>/', cartoon_genre_view, name='cartoon_genre_ist'),
    path('anime_genre/<str:url>/', anime_genre_view, name='anime_genre_ist'),
    path('add-rating/', AddStarRating.as_view(), name = 'add_rating'),
    path('json-filter/', JsonFilterView.as_view(), name = 'json_filter'),
    path('<str:slug>/', MovieDetailView.as_view(), name = 'movie_detail'),
    path('series/<str:slug>/', SeriesDetailView.as_view(), name = 'series_detail'),
    path('cartoon/<str:slug>/', CartoonDetailView.as_view(), name = 'cartoon_detail'),
    path('anime/<str:slug>/', AnimeDetailView.as_view(), name = 'anime_detail'),
    path('review/<int:pk>/', AddReview.as_view(), name = 'add_review'),
    path('series-review/<int:pk>/', SeriesAddReview.as_view(), name = 'series_add_review'),
    path('cartoon-review/<int:pk>/', CartoonAddReview.as_view(), name = 'cartoon_add_review'),
    path('cartoon-review/<int:pk>/', AnimeAddReview.as_view(), name = 'anime_add_review'),
    path('actor/<str:slug>/', ActorView.as_view(), name = 'actor_detail'),

    
    

    

]

online_theater/online_theater/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.movie.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('videos/', include('apps.user.urls')),
    

]


urlpatterns += i18n_patterns(


)


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
     

online_theater/apps/movie/models.py
from statistics import mode
from django.db import models
from datetime import date
from django.urls import reverse
from embed_video.fields import EmbedVideoField


class Category(models.Model):
    title = models.CharField('Категория',max_length=255,)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=255)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


   





class Actor(models.Model):
    name = models.CharField(max_length=255)
    age = models.PositiveIntegerField('Age', default=0)
    descrption = models.TextField('descrption')
    image = models.ImageField(upload_to = 'actors/')
    url = models.SlugField(max_length=255)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Actor'
        verbose_name_plural = 'Actors'




class Genre_movie(models.Model):
    title = models.CharField(max_length = 255)
    descrption = models.TextField()
    url = models.SlugField(max_length=255, unique = True)

    def __str__(self):
        return self.title

    

    class Meta:
        verbose_name = 'Movie genre'
        verbose_name_plural = 'Movie genres'

    


class MovieVideo(models.Model):

    video = models.FileField(upload_to='movies/video/%y')








class Movie(models.Model):

    title = models.CharField(max_length = 255)
    tagline = models.CharField('Слоган', max_length = 255, ) 
    description = models.TextField()
    poster = models.ImageField(upload_to = 'movies/')
    year = models.PositiveIntegerField('дата выхода', default = 2022)
    country = models.CharField(max_length=255)
    directors = models.ManyToManyField(Actor, verbose_name='режисёр', related_name = 'movie_director')
    actors = models.ManyToManyField(Actor, verbose_name='актеры', related_name='movie_actor')
    genres = models.ManyToManyField(Genre_movie, verbose_name = 'жанры', related_name='get_movie_genres')
    world_premier = models.DateField(default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default = 0, help_text = 'указать сумму в долларах')
    fees_in_usa = models.PositiveIntegerField('Сборы в США', default=0, help_text='указать сумму в долларах')
    fees_in_world = models.PositiveIntegerField('сборы в мире', default=0, help_text='указать сумму в долларах')
    videos = models.OneToOneField(MovieVideo, on_delete=models.CASCADE, related_name='movie_videos')
    url = models.SlugField(max_length=255, unique=True)
    draft = models.BooleanField('Черновик', default=False)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs = {'slug': self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull = True)

    class Meta:
        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'





    





    
class Genre_series(models.Model):
    title = models.CharField(max_length = 255)
    descrption = models.TextField()
    url = models.SlugField(max_length=255, unique = True)

    def __str__(self):
        return self.title

    

    class Meta:
        verbose_name = 'Series genre'
        verbose_name_plural = 'Series genres'

class SeriesVideo(models.Model):

    video = models.FileField(upload_to='series/video/%y')




class Series(models.Model):

    title = models.CharField(max_length = 255)
    genres = models.ManyToManyField(Genre_series, verbose_name = 'жанры', related_name='get_series_genres')
    tagline = models.CharField('Слоган', max_length = 255, ) 
    description = models.TextField()
    poster = models.ImageField(upload_to = 'movies/')
    year = models.PositiveIntegerField('дата выхода', default = 2022)
    country = models.CharField(max_length=255)
    world_premier = models.DateField(default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default = 0, help_text = 'указать сумму в долларах')
    fees_in_usa = models.PositiveIntegerField('Сборы в США', default=0, help_text='указать сумму в долларах')
    fees_in_world = models.PositiveIntegerField('сборы в мире', default=0, help_text='указать сумму в долларах')
    videos = models.OneToOneField(SeriesVideo, on_delete=models.CASCADE, related_name='series_videos')
    url = models.SlugField(max_length=255, unique=True)
    draft = models.BooleanField('Черновик', default=False)

    def __str__(self) -> str:
        return self.title

    def get_series_review(self):
        return self.reviews_set_series.filter(parent__isnull = True)
    
    def get_absolute_url_series(self):
        return reverse('series_detail', kwargs = {'slug': self.url})




class Genre_cartoon(models.Model):
    title = models.CharField(max_length = 255)
    descrption = models.TextField()
    url = models.SlugField(max_length=255, unique = True)

    def __str__(self):
        return self.title

    

    class Meta:
        verbose_name = 'Cartoon genre'
        verbose_name_plural = 'Cartoon genres'


class CartoonVideo(models.Model):

    video = models.FileField(upload_to='cartoon/video/%y')


class Cartoon(models.Model):

    title = models.CharField(max_length = 255)
    genres = models.ManyToManyField(Genre_cartoon, verbose_name = 'жанры', related_name='get_cartoon_genres')
    tagline = models.CharField('Слоган', max_length = 255, ) 
    description = models.TextField()
    poster = models.ImageField(upload_to = 'movies/')
    year = models.PositiveIntegerField('дата выхода', default = 2022)
    country = models.CharField(max_length=255)
    url = models.SlugField(max_length=255, unique=True)
    world_premier = models.DateField(default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default = 0, help_text = 'указать сумму в долларах')
    fees_in_usa = models.PositiveIntegerField('Сборы в США', default=0, help_text='указать сумму в долларах')
    fees_in_world = models.PositiveIntegerField('сборы в мире', default=0, help_text='указать сумму в долларах')
    videos = models.OneToOneField(CartoonVideo, on_delete=models.CASCADE, related_name='movie_videos')
    draft = models.BooleanField('Черновик', default=False)


    def __str__(self) -> str:
        return self.title


    def get_cartoon_review(self):
        return self.reviews_set_cartoon.filter(parent__isnull = True)

    def get_absolute_url_cartoon(self):
        return reverse('cartoon_detail', kwargs = {'slug': self.url})

 

class Genre_anime(models.Model):
    title = models.CharField(max_length = 255)
    descrption = models.TextField()
    url = models.SlugField(max_length=255, unique = True)
    

    def __str__(self):
        return self.title

    

    class Meta:
        verbose_name = 'Anime genre'
        verbose_name_plural = 'Anime genres'


class AnimeVideo(models.Model):

    video = models.FileField(upload_to='video/%y')

class Anime(models.Model):

    title = models.CharField(max_length = 255)
    genres = models.ManyToManyField(Genre_anime, verbose_name = 'жанры', related_name='get_anime_genres')
    url = models.SlugField(max_length=255, unique=True)
    tagline = models.CharField('Слоган', max_length = 255, ) 
    description = models.TextField()
    poster = models.ImageField(upload_to = 'movies/')
    year = models.PositiveIntegerField('дата выхода', default = 2022)
    country = models.CharField(max_length=255)
    world_premier = models.DateField(default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default = 0, help_text = 'указать сумму в долларах')
    fees_in_usa = models.PositiveIntegerField('Сборы в США', default=0, help_text='указать сумму в долларах')
    fees_in_world = models.PositiveIntegerField('сборы в мире', default=0, help_text='указать сумму в долларах')
    videos = models.OneToOneField(AnimeVideo, on_delete=models.CASCADE, related_name='movie_videos')
    draft = models.BooleanField('Черновик', default=False)
    
    def __str__(self) -> str:
        return self.title

    def get_ainme_review(self):
        return self.reviews_set_anime.filter(parent__isnull = True)

    def get_absolute_url_anime(self):
        return reverse('anime_detail', kwargs = {'slug': self.url})



class AllData(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    cartoon = models.ForeignKey(Cartoon, on_delete=models.CASCADE)
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE)
 


class MovieShots(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to = 'movie_shots')
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title 

    class Meta:
        verbose_name = 'Кадр из фильма'
        verbose_name_plural = 'Кадры из фильма'



class RatingStar(models.Model):
    value = models.PositiveIntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.value}'

    class Meta:
        verbose_name = 'Звезда рейтинга'
        verbose_name_plural = 'Звезды рейтинга'
        ordering = ["-value"]




class Rating(models.Model):
    ip = models.CharField(max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='звезда')
    movie = models.ForeignKey(Movie, on_delete=models.CharField, verbose_name='фильм')

    def __str__(self) -> str:
        return f'Рейтинг: {self.movie} - {self.star} '

    class Meta:
        verbose_name = ' рейтинг'
        verbose_name_plural = 'рейтинги'
    



class Review(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=255)
    text = models.TextField("Отзыв" ,max_length=5000)
    parent = models.ForeignKey('self', verbose_name='Подотзыв', on_delete=models.SET_NULL, blank=True, null=True, related_name='comments_comment',)

online_theater/apps/movie/forms.py
from django import forms
from .models import Review, Rating, RatingStar, SeriesReview, CartoonReview,  AnimeReiview

class ReviewForm(forms.ModelForm):
    """Форма отзыва"""
    class Meta:
        model = Review
        fields = ('name', 'email', 'text')



class SeriesReviewForm(forms.ModelForm):
    """Форма отзыва"""
    class Meta:
        model = SeriesReview
        fields = ('name', 'email', 'text')



class CartoonReviewForm(forms.ModelForm):
    """Форма отзыва"""
    class Meta:
        model = CartoonReview
        fields = ('name', 'email', 'text')




class AnimeReviewForm(forms.ModelForm):
    """Форма отзыва"""
    class Meta:
        model = AnimeReiview
        fields = ('name', 'email', 'text')


class RatingForm(forms.ModelForm):
    star = forms.ModelChoiceField(
        queryset = RatingStar.objects.all(), widget = forms.RadioSelect(), empty_label = None
    )

    class Meta:
        model = Rating
        fields = ('star',)

online_theater/templates/movie/actor.html
{% extends 'movie/base.html' %}
{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Возраст:</b> {{ actor.age }} лет</span></li>
                    <li>
                        <span><b>Режиссер:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                    <li><span><b>Актер:</b>
                        {% for movie in actor.film_actor.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                О {{ actor.name }}
            </h3>
            <p class="editContent">
                {{ actor.description|safe }}
            </p>
        </div>
    </div>
{% endblock movie %}

online_theater/templates/movie/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
            {% block series %}
            {% endblock series %}
            {% block cartoon %}
            {% endblock cartoon %}
            {% block animes %}
            {% endblock animes %}
        </div>
        </div>
    </section>

    
{% endblock content %}

online_theater/templates/movie/movie_detail.html
{% extends 'movie/base.html' %}
{% load static %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><b>Год:</b> {{ movie.year }}</span></li>
                    <li style="list-style: none">
                        <span><b>Страна:</b> {{ movie.country }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Слоган:</b> {{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Режиссер:</b>
                            {% for director in movie.directors.all %}
                                <a href="{% url 'actor_detail' director.name %}">
                                    {{ director.name }} |
                                </a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none"><span><b>Актеры:</b>
                        {% for actor in movie.actors.all %}
                            <a href="{% url 'actor_detail' actor.name %}">
                                    {{ actor.name }} |
                            </a>
                        {% endfor %}
                                </span>
                    </li>
                    <li style="list-style: none"><span><b>Жанр:</b>
                        
                        {% for genre in movie.genres.all %}
                        <a href="{% url 'filter'  %}"></a>
                            {{ genre.title}} |
                        {% endfor %}
                                    </span>
                    </li>
                    <li>
                        <span><b>Премьера в мире:</b> {{ movie.world_premier }}</span>
                    </li>
                    <li>
                        <span><b>Бюджет:</b> ${{ movie.budget }}</span></li>
                    <li>
                        <span><b>Сборы в США:</b> ${{ movie.fees_in_usa }}</span></li>
                    <li>
                        <span><b>Сборы в мире:</b> ${{ movie.fess_in_world }}</span>
                    </li>
                    <li>
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <b>Рейтинг:</b>
                            {% csrf_token %}
                            <input type="hidden" value="{{ movie.id }}" name="movie">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                            
                        </form>
                    </li>
                </ul>

                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                    <span class="fa fa-facebook-f"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent">
                                    <span class="fa fa-twitter"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                    <span class="fa fa-vk"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent">
                О фильме {{ movie.title }}
            </h3>
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots "
                         alt="{{ image.description }}">
                {% endfor %}
            </p>
            <p class="editContent">
                {{ movie.description|safe }}
            </p>
        </div>

                <html>	
                    <head>
                        <script src="http://code.jquery.com/jquery-1.8.3.js"></script>   <!-- jQuery -->
                        <script src="https://www.youtube.com/iframe_api"></script> <!-- Здесь цепляем кода iframe_api-->
                        <link rel='stylesheet' id='fortunato-style-css'  href='http://your.styles.css' type='text/css' media='' /> <!-- стили (в отдельном куске css кода)-->
                        </head>
                    <body>	   
                        <video>
                        <div class="panel">
                        <button id="back" onclick="player.previousVideo();">Back</button>
                        <button id="play" onclick="player.playVideo();">Play</button>
                        <button id="pause" onclick="player.pauseVideo();">Pause</button>
                        <button id="next" onclick="player.nextVideo();">Next</button>
                        <div id="time">00:00</div>		
                        <div id="line" onclick="progress (event);">
                        <div class="viewed"></div>
                        <div id="fader" onclick="alert('fader');"></div>
                        </div>
                        <button id="volume" onclick="editVolume ();">Громкость</button>
                        <div id="quality">Auto</div>
                        <button id="full" onclick="playFullscreen ();">FullScreen</button>
                        </div>		
                        <div>
                        <button id="playlist" onclick="loadPlaylistVideoIds();">Load New Playlist</button>
                        <button id="qual" onclick="editQuality ();">Сменить качество на 480</button>
                        </div>
                    </video>
                    </body>	
                </html>


        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent">
                        <span class="sub-tittle editContent">{{ movie.reviews_set.count }}</span>Оставить
                        отзыв</h3>
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4"
                          id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий *
                            </label>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    Имя *
                                </label>
                                <input type="text" class="form-control border" name="name"
                                       id="contactusername" required="">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                <input type="email" class="form-control border" name="email"
                                       id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
        {% for review in movie.get_review %}
            <div class="media py-5">

                <img src="{{ user.account_set.all.get_avatar_url }}" class="mr-3 img-fluid" alt="image">
                
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview"
                       onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    {% for rew in review.comments_comment.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="" class="img-fluid "
                                     alt="image">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                <p class="mt-2 editContent">{{ rew.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
    <script>
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }

    </script>
{% endblock movie %}


<pjsdiv style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; transition: transform 0.2s linear 0s; text-align: center;">
    <video preload="none" crossorigin="anonymous" src="" x-webkit-airplay="allow" disableremoteplayback="true" controlslist="nodownload" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: contain; transition: filter 0.2s linear 0s; min-height: auto; max-height: none; min-width: auto; max-width: none;">
    </video>
</pjsdiv>

online_theater/templates/movie/movie_list.html
{% extends 'movie/base.html' %}
{% block title %} {% endblock title %}
{% block header %}  {% endblock header %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{% url 'movie_detail' movie.url %}"
                                   class="editContent">
                                    {{ movie.title }}
                                </a>
                            </h4>

                            

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                                
                    </div>
                </div>
            {% endfor %}
        </div>

        
{% endblock movie %}



                                